project_name: lanup

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: lanup
    binary: lanup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/raucheacho/lanup/cmd.Version={{.Version}}

archives:
  - id: lanup
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

# Homebrew
brews:
  - name: lanup
    repository:
      owner: raucheacho
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/raucheacho/lanup
    description: "Automatically expose your local backend services on your local network"
    license: MIT
    test: |
      system "#{bin}/lanup --version"
    install: |
      bin.install "lanup"

# Scoop
scoops:
  - repository:
      owner: raucheacho
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    homepage: https://github.com/raucheacho/lanup
    description: "Automatically expose your local backend services on your local network"
    license: MIT

# NPM (via pkg)
nfpms:
  - id: lanup
    package_name: lanup
    vendor: raucheacho
    homepage: https://github.com/raucheacho/lanup
    maintainer: raucheacho <your-email@example.com>
    description: "Automatically expose your local backend services on your local network"
    license: MIT
    formats:
      - deb
      - rpm
      - apk

release:
  github:
    owner: raucheacho
    name: lanup
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
