baseURL = "https://raucheacho.github.io/lanup/"
languageCode = "en-us"
title = "lanup - Local Network Service Exposure"
theme = "book"

[params]
  description = "Automatically expose your local backend services on your local network"
  author = "raucheacho"
  github = "https://github.com/raucheacho/lanup"

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 1
  
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/raucheacho/lanup"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
